server.port=8180

# OpenSearch connection (existing)
opensearch.host=localhost
opensearch.port=9200
opensearch.scheme=http
# If your cluster requires auth, set username/password; leave empty otherwise
opensearch.username=
opensearch.password=

# Enable bean overriding if needed
spring.main.allow-bean-definition-overriding=true

# PostgreSQL datasource for MigrationController (adjust as needed)
spring.datasource.url=jdbc:postgresql://localhost:5432/zimperium
spring.datasource.username=zimperium
spring.datasource.password=Zimperium!!1
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
#Formats SQL for readability.
spring.jpa.properties.hibernate.format_sql=true
#Prints SQL queries to the console.
#spring.jpa.show-sql=true

#springdoc.swagger-ui.url=/OpenAPI.yaml
springdoc.swagger-ui.use-root-path=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.data.jpa.repositories.enabled=true

# Spring Data Elasticsearch connection (used by ElasticsearchRepository)
# You can specify a single URI or a comma-separated list
#spring.elasticsearch.uris=http://localhost:9200
# Optional basic auth
#spring.elasticsearch.username=
#spring.elasticsearch.password=

#(logs SQL statements)
logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.root=INFO

#Logs query parameter values.
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE